// src/lib/mockMovies.ts
import Crown from "@/assets/posters/crown.jpg";
import ShawshankRedemption from "@/assets/posters/Shawshank-Redemption.jpg";
import Godfather from "@/assets/posters/Godfather.jpg";
import DarkKnight from "@/assets/posters/darknight.jpg";
import Inception from "@/assets/posters/Inception.jpg";
import Interstellar from "@/assets/posters/interstellar.jpeg";
import PulpFiction from "@/assets/posters/pulp-fiction.jpg";
import FightClub from "@/assets/posters/fight.jpg";
import ForrestGump from "@/assets/posters/Forrest-Gump.jpg";
import Matrix from "@/assets/posters/matrix.jpg";
import Goodfellas from "@/assets/posters/Goodfellas.jpg";
import StrangerThings from "@/assets/posters/Stranger-things.jpg";
import BreakingBad from "@/assets/posters/Breaking-Bad.jpg";
import GameOfThrones from "@/assets/posters/Game-of-Thrones.jpg";
import TheMandalorian from "@/assets/posters/The-Mandalorian.jpg";
import Witcher from "@/assets/posters/Witcher.jpg";
import Office from "@/assets/posters/Office.jpg";
import Friends from "@/assets/posters/Friends.jpg";
import Sherlock from "@/assets/posters/Sherlock.jpg";
import TheWalkingDead from "@/assets/posters/The-Walking-Dead.jpg";
import BigBangTheory from "@/assets/posters/The-Big-Bang-Theory.jpg";
import HouseOfCards from "@/assets/posters/House-of-Cards.jpg";
import BlackMirror from "@/assets/posters/Black-Mirror.jpg";
import PeakyBlinders from "@/assets/posters/Peaky-Blinders.jpg";
import TheLastOfUs from "@/assets/posters/The-Last-of-Us.jpg";
import Succession from "@/assets/posters/Succession.jpg";
import Mindhunter from "@/assets/posters/Mindhunter.jpg";
import Ozark from "@/assets/posters/Ozark.jpg";
import TheExpanse from "@/assets/posters/The-Expanse.jpg";
import TheHandmaidsTale from "@/assets/posters/The-Handmaids-Tale.jpg";
import BetterCallSaul from "@/assets/posters/Better-Call-Saul.jpg";
import TheBoys from "@/assets/posters/Boys.jpg";
import TheSopranos from "@/assets/posters/The-Sopranos.jpg";
import TheWire from "@/assets/posters/The-Wire.jpg";
import Westworld from "@/assets/posters/Westworld.jpg";
import TheAmericans from "@/assets/posters/The-Americans.jpg";
import MadMen from "@/assets/posters/Mad-Men.jpg";
import TheXFiles from "@/assets/posters/The-X‑Files.jpg";
import BattlestarGalactica from "@/assets/posters/Battlestar-Galactica.jpg";
import Dexter from "@/assets/posters/Dexter.jpg";
import Homeland from "@/assets/posters/Homeland.jpg";
import Narcos from "@/assets/posters/Narcos.jpg";
import TheMarvelousMrsMaisel from "@/assets/posters/The-Marvelous-Mrs-Maisel.jpg";
import TheGoodPlace from "@/assets/posters/The-Good-Place.jpg";
import BrooklynNineNine from "@/assets/posters/Brooklyn.jpg";
import TheHauntingOfHillHouse from "@/assets/posters/The-Haunting-of-Hill-House.jpg";
import ThePacific from "@/assets/posters/The-Pacific.jpg";
import BoardwalkEmpire from "@/assets/posters/Boardwalk-Empire.jpg";
import TheLeftovers from "@/assets/posters/The Leftovers.jpg";
import TwinPeaksPoster from "@/assets/posters/Twin-Peaks.jpg";
import sheep from "@/assets/posters/sheep.jpg";
import nurnberg from "@/assets/posters/nurnberg.jpg";
import hail from "@/assets/posters/hail.jpg";

export const mockMovies = [
  {
    id: 1,
    title: "The Crown",
    year: 2016,
    genre: ["Drama"],
    rating: 8.3,
    description:
      "The gripping, decades‑spanning inside story of Her Majesty Queen Elizabeth II and the Prime Ministers who shaped Britain's post‑war destiny.",
    poster: Crown,
    creator: "Peter Morgan",
    cast: ["Imelda Staunton", "Jonathan Pryce", "Lesley Manville"],
    seasons: 6,
    episodes: 60,
    language: "English",
  },
  {
    id: 2,
    title: "The Shawshank Redemption",
    year: 1994,
    genre: ["Drama"],
    rating: 9.3,
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    poster: ShawshankRedemption,
    creator: "Frank Darabont",
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    seasons: 1,
    episodes: 1,
    language: "English",
  },
  {
    id: 3,
    title: "The Godfather",
    year: 1972,
    genre: ["Crime", "Drama"],
    rating: 9.2,
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    poster: Godfather,
    creator: "Francis Ford Coppola",
    cast: ["Marlon Brando", "Al Pacino", "James Caan"],
    seasons: 1,
    episodes: 1,
    language: "English",
  },
  {
    id: 4,
    title: "The Dark Knight",
    year: 2008,
    genre: ["Action", "Crime", "Drama"],
    rating: 9.0,
    description:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    poster: DarkKnight,
    creator: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    seasons: 1,
    episodes: 1,
    language: "English",
  },
  {
    id: 5,
    title: "Inception",
    year: 2010,
    genre: ["Action", "Sci-Fi", "Thriller"],
    rating: 8.8,
    description:
      "A thief who steals corporate secrets through the use of dream‑sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
    poster: Inception,
    creator: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon‑Levitt", "Elliot Page"],
    seasons: 1,
    episodes: 1,
    language: "English",
  },
  {
    id: 6,
    title: "Interstellar",
    year: 2014,
    genre: ["Adventure", "Drama", "Sci-Fi"],
    rating: 8.7,
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    poster: Interstellar,
    creator: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    seasons: 1,
    episodes: 1,
    language: "English",
  },
  {
    id: 7,
    title: "Pulp Fiction",
    year: 1994,
    genre: ["Crime", "Drama"],
    rating: 8.9,
    description:
      "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    poster: PulpFiction,
    creator: "Quentin Tarantino",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    seasons: 1,
    episodes: 1,
    language: "English",
  },
  {
    id: 8,
    title: "Fight Club",
    year: 1999,
    genre: ["Drama"],
    rating: 8.8,
    description:
      "An insomniac office worker and a devil‑may‑care soap maker form an underground fight club that evolves into something much more.",
    poster: FightClub,
    creator: "David Fincher",
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    seasons: 1,
    episodes: 1,
    language: "English",
  },
  {
    id: 9,
    title: "Forrest Gump",
    year: 1994,
    genre: ["Comedy", "Drama", "Romance"],
    rating: 8.8,
    description:
      "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
    poster: ForrestGump,
    creator: "Robert Zemeckis",
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
    seasons: 1,
    episodes: 1,
    language: "English",
  },
  {
    id: 10,
    title: "The Matrix",
    year: 1999,
    genre: ["Action", "Sci-Fi"],
    rating: 8.7,
    description:
      "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    poster: Matrix,
    creator: "Lana Wachowski, Lilly Wachowski",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie‑Anne Moss"],
    seasons: 1,
    episodes: 1,
    language: "English",
  },
  {
    id: 11,
    title: "Goodfellas",
    year: 1990,
    genre: ["Crime", "Drama"],
    rating: 8.7,
    description:
      "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.",
    poster: Goodfellas,
    creator: "Martin Scorsese",
    cast: ["Robert De Niro", "Ray Liotta", "Joe Pesci"],
    seasons: 1,
    episodes: 1,
    language: "English",
  },
  {
    id: 12,
    title: "Stranger Things",
    year: 2016,
    genre: ["Sci-Fi", "Horror"],
    rating: 8.7,
    description:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    poster: StrangerThings,
    creator: "The Duffer Brothers",
    cast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder"],
    seasons: 4,
    episodes: 34,
    language: "English",
  },
  {
    id: 13,
    title: "Breaking Bad",
    year: 2008,
    genre: ["Crime", "Drama"],
    rating: 9.5,
    description:
      "A high school chemistry teacher turned methamphetamine manufacturer partners with a former student to secure his family's future after being diagnosed with lung cancer.",
    poster: BreakingBad,
    creator: "Vince Gilligan",
    cast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn"],
    seasons: 5,
    episodes: 62,
    language: "English",
  },
  {
    id: 14,
    title: "Game of Thrones",
    year: 2011,
    genre: ["Fantasy", "Drama"],
    rating: 9.2,
    description:
      "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
    poster: GameOfThrones,
    creator: "David Benioff, D.B. Weiss",
    cast: ["Emilia Clarke", "Kit Harington", "Peter Dinklage"],
    seasons: 8,
    episodes: 73,
    language: "English",
  },
  {
    id: 15,
    title: "The Mandalorian",
    year: 2019,
    genre: ["Sci-Fi", "Adventure"],
    rating: 8.7,
    description:
      "A lone bounty hunter travels the outer reaches of the galaxy, far from the authority of the New Republic, in this Star Wars spin‑off.",
    poster: TheMandalorian,
    creator: "Jon Favreau",
    cast: ["Pedro Pascal", "Gina Carano", "Carl Weathers"],
    seasons: 3,
    episodes: 24,
    language: "English",
  },
  {
    id: 16,
    title: "The Witcher",
    year: 2019,
    genre: ["Fantasy", "Action"],
    rating: 8.2,
    description:
      "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
    poster: Witcher,
    creator: "Lauren Schmidt Hissrich",
    cast: ["Henry Cavill", "Anya Chalotra", "Freya Allan"],
    seasons: 3,
    episodes: 24,
    language: "English",
  },
  {
    id: 17,
    title: "The Office (US)",
    year: 2005,
    genre: ["Comedy"],
    rating: 9.0,
    description:
      "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
    poster: Office,
    creator: "Greg Daniels",
    cast: ["Steve Carell", "John Krasinski", "Jenna Fischer"],
    seasons: 9,
    episodes: 201,
    language: "English",
  },
  {
    id: 18,
    title: "Friends",
    year: 1994,
    genre: ["Comedy", "Romance"],
    rating: 8.9,
    description:
      "Follows the personal and professional lives of six twenty‑something friends living in Manhattan.",
    poster: Friends,
    creator: "David Crane, Marta Kauffman",
    cast: ["Jennifer Aniston", "Courteney Cox", "Lisa Kudrow"],
    seasons: 10,
    episodes: 236,
    language: "English",
  },
  {
    id: 19,
    title: "Sherlock",
    year: 2010,
    genre: ["Mystery", "Crime"],
    rating: 9.1,
    description:
      "A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.",
    poster: Sherlock,
    creator: "Mark Gatiss, Steven Moffat",
    cast: ["Benedict Cumberbatch", "Martin Freeman", "Una Stubbs"],
    seasons: 4,
    episodes: 13,
    language: "English",
  },
  {
    id: 20,
    title: "The Walking Dead",
    year: 2010,
    genre: ["Horror", "Drama"],
    rating: 8.1,
    description:
      "Sheriff Deputy Rick Grimes awakens from a coma to find a post‑apocalyptic world overrun by zombies, and must lead a group of survivors.",
    poster: TheWalkingDead,
    creator: "Frank Darabont",
    cast: ["Andrew Lincoln", "Norman Reedus", "Danai Gurira"],
    seasons: 11,
    episodes: 177,
    language: "English",
  },
  {
    id: 21,
    title: "The Big Bang Theory",
    year: 2007,
    genre: ["Comedy"],
    rating: 8.1,
    description:
      "A woman who moves into an apartment next door to two brilliant but socially awkward physicists shows them how little they know about life outside the lab.",
    poster: BigBangTheory,
    creator: "Chuck Lorre, Bill Prady",
    cast: ["Johnny Galecki", "Jim Parsons", "Kaley Cuoco"],
    seasons: 12,
    episodes: 279,
    language: "English",
  },
  {
    id: 22,
    title: "House of Cards",
    year: 2013,
    genre: ["Drama", "Thriller"],
    rating: 8.6,
    description:
      "A ruthless politician will stop at nothing to conquer Washington, D.C., in this American adaptation of the BBC series.",
    poster: HouseOfCards,
    creator: "Beau Willimon",
    cast: ["Kevin Spacey", "Robin Wright", "Michael Kelly"],
    seasons: 6,
    episodes: 73,
    language: "English",
  },
  {
    id: 23,
    title: "Black Mirror",
    year: 2011,
    genre: ["Sci-Fi", "Thriller"],
    rating: 8.7,
    description:
      "An anthology series exploring a twisted, high‑tech multiverse where humanity's greatest innovations and darkest instincts collide.",
    poster: BlackMirror,
    creator: "Charlie Brooker",
    cast: ["Various"],
    seasons: 6,
    episodes: 27,
    language: "English",
  },
  {
    id: 24,
    title: "Peaky Blinders",
    year: 2013,
    genre: ["Crime", "Drama"],
    rating: 8.8,
    description:
      "A gangster family epic set in 1919 Birmingham, England, centered on a gang who sew razor blades in the peaks of their caps.",
    poster: PeakyBlinders,
    creator: "Steven Knight",
    cast: ["Cillian Murphy", "Helen McCrory", "Paul Anderson"],
    seasons: 6,
    episodes: 36,
    language: "English",
  },
  {
    id: 25,
    title: "The Last of Us",
    year: 2023,
    genre: ["Drama", "Adventure"],
    rating: 8.9,
    description:
      "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14‑year‑old girl who may be humanity's last hope.",
    poster: TheLastOfUs,
    creator: "Craig Mazin, Neil Druckmann",
    cast: ["Pedro Pascal", "Bella Ramsey", "Anna Torv"],
    seasons: 1,
    episodes: 9,
    language: "English",
  },
  {
    id: 26,
    title: "Succession",
    year: 2018,
    genre: ["Drama", "Comedy"],
    rating: 8.8,
    description:
      "The Roy family, owners of a global media empire, fight for control of the company amidst uncertainty about the health of their patriarch.",
    poster: Succession,
    creator: "Jesse Armstrong",
    cast: ["Brian Cox", "Jeremy Strong", "Sarah Snook"],
    seasons: 4,
    episodes: 39,
    language: "English",
  },
  {
    id: 27,
    title: "Mindhunter",
    year: 2017,
    genre: ["Crime", "Thriller"],
    rating: 8.6,
    description:
      "Two FBI agents in the 1970s delve into the psychology of serial killers and develop investigative techniques that would become modern criminal profiling.",
    poster: Mindhunter,
    creator: "Joe Penhall",
    cast: ["Jonathan Groff", "Holt McCallany", "Anna Torv"],
    seasons: 2,
    episodes: 19,
    language: "English",
  },
  {
    id: 28,
    title: "Ozark",
    year: 2017,
    genre: ["Crime", "Drama"],
    rating: 8.4,
    description:
      "A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug lord.",
    poster: Ozark,
    creator: "Bill Dubuque, Mark Williams",
    cast: ["Jason Bateman", "Laura Linney", "Sofia Hublitz"],
    seasons: 4,
    episodes: 44,
    language: "English",
  },
  {
    id: 29,
    title: "The Expanse",
    year: 2015,
    genre: ["Sci-Fi", "Mystery"],
    rating: 8.5,
    description:
      "In a future where humanity has colonized the solar system, a conspiracy threatens to destroy the fragile peace between Earth, Mars, and the Belt.",
    poster: TheExpanse,
    creator: "Mark Fergus, Hawk Ostby",
    cast: ["Steven Strait", "Dominique Tipper", "Wes Chatham"],
    seasons: 6,
    episodes: 62,
    language: "English",
  },
  {
    id: 30,
    title: "The Handmaid's Tale",
    year: 2017,
    genre: ["Drama", "Sci-Fi"],
    rating: 8.4,
    description:
      "In a dystopian future, a woman is forced to live as a concubine under a fundamentalist theocratic dictatorship.",
    poster: TheHandmaidsTale,
    creator: "Bruce Miller",
    cast: ["Elisabeth Moss", "Joseph Fiennes", "Yvonne Strahovski"],
    seasons: 5,
    episodes: 56,
    language: "English",
  },
  {
    id: 31,
    title: "Better Call Saul",
    year: 2015,
    genre: ["Crime", "Drama"],
    rating: 8.8,
    description:
      "The prequel to Breaking Bad follows small‑time lawyer Jimmy McGill as he transforms into the morally challenged lawyer Saul Goodman.",
    poster: BetterCallSaul,
    creator: "Vince Gilligan, Peter Gould",
    cast: ["Bob Odenkirk", "Rhea Seehorn", "Jonathan Banks"],
    seasons: 6,
    episodes: 63,
    language: "English",
  },
  {
    id: 32,
    title: "The Boys",
    year: 2019,
    genre: ["Action", "Comedy", "Sci-Fi"],
    rating: 8.7,
    description:
      "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.",
    poster: TheBoys,
    creator: "Eric Kripke",
    cast: ["Karl Urban", "Jack Quaid", "Antony Starr"],
    seasons: 4,
    episodes: 32,
    language: "English",
  },
  {
    id: 33,
    title: "The Sopranos",
    year: 1999,
    genre: ["Crime", "Drama"],
    rating: 9.2,
    description:
      "A New Jersey mob boss struggles to balance his personal and professional lives while dealing with his dysfunctional family and the demands of the mafia.",
    poster: TheSopranos,
    creator: "David Chase",
    cast: ["James Gandolfini", "Edie Falco", "Michael Imperioli"],
    seasons: 6,
    episodes: 86,
    language: "English",
  },
  {
    id: 34,
    title: "The Wire",
    year: 2002,
    genre: ["Crime", "Drama"],
    rating: 9.3,
    description:
      "A gritty portrayal of the drug trade in Baltimore, told from the perspectives of both law enforcement and those on the street.",
    poster: TheWire,
    creator: "David Simon",
    cast: ["Dominic West", "Lance Reddick", "Michael K. Williams"],
    seasons: 5,
    episodes: 60,
    language: "English",
  },
  {
    id: 35,
    title: "Westworld",
    year: 2016,
    genre: ["Sci-Fi", "Drama"],
    rating: 8.5,
    description:
      "In a futuristic theme park, guests interact with lifelike robots, but the park's creators soon realize that the robots are becoming sentient.",
    poster: Westworld,
    creator: "Jonathan Nolan, Lisa Joy",
    cast: ["Evan Rachel Wood", "Jeffrey Wright", "Ed Harris"],
    seasons: 4,
    episodes: 36,
    language: "English",
  },
  {
    id: 36,
    title: "The Americans",
    year: 2013,
    genre: ["Drama", "Thriller"],
    rating: 8.4,
    description:
      "Two Soviet spies pose as a married American couple in Washington D.C. during the Cold War, living a double life with their children.",
    poster: TheAmericans,
    creator: "Joe Weisberg",
    cast: ["Keri Russell", "Matthew Rhys", "Keidrich Sellati"],
    seasons: 6,
    episodes: 75,
    language: "English",
  },
  {
    id: 37,
    title: "Mad Men",
    year: 2007,
    genre: ["Drama"],
    rating: 8.6,
    description:
      "Set in the 1960s, this drama follows the lives of the staff at a prestigious New York advertising agency.",
    poster: MadMen,
    creator: "Matthew Weiner",
    cast: ["Jon Hamm", "Elisabeth Moss", "Vincent Kartiser"],
    seasons: 7,
    episodes: 92,
    language: "English",
  },
  {
    id: 38,
    title: "The X‑Files",
    year: 1993,
    genre: ["Sci-Fi", "Mystery"],
    rating: 8.6,
    description:
      "Two FBI agents investigate unsolved cases involving paranormal phenomena, often uncovering a government conspiracy.",
    poster: TheXFiles,
    creator: "Chris Carter",
    cast: ["David Duchovny", "Gillian Anderson", "Mitch Pileggi"],
    seasons: 11,
    episodes: 218,
    language: "English",
  },
  {
    id: 39,
    title: "Twin Peaks",
    year: 1990,
    genre: ["Drama", "Mystery"],
    rating: 8.8,
    description:
      "An FBI agent descends into the bizarre and supernatural world of a small town after the murder of a popular high school girl.",
    poster: TwinPeaksPoster,
    creator: "Mark Frost, David Lynch",
    cast: ["Kyle MacLachlan", "Sheryl Lee", "Michael Ontkean"],
    seasons: 3,
    episodes: 48,
    language: "English",
  },
  {
    id: 40,
    title: "Battlestar Galactica",
    year: 2004,
    genre: ["Sci-Fi", "Adventure"],
    rating: 8.7,
    description:
      "In a distant galaxy, the last remnants of humanity flee the genocidal Cylons while searching for the mythical planet Earth.",
    poster: BattlestarGalactica,
    creator: "Ronald D. Moore",
    cast: ["Edward James Olmos", "Mary McDonnell", "Jamie Bamber"],
    seasons: 4,
    episodes: 73,
    language: "English",
  },
  {
    id: 41,
    title: "Dexter",
    year: 2006,
    genre: ["Crime", "Drama", "Thriller"],
    rating: 8.6,
    description:
      "A blood‑spatter analyst for the Miami police secretly moonlights as a vigilante serial killer who targets other murderers.",
    poster: Dexter,
    creator: "James Manos Jr.",
    cast: ["Michael C. Hall", "Jennifer Carpenter", "Desmond Harrington"],
    seasons: 8,
    episodes: 96,
    language: "English",
  },
  {
    id: 42,
    title: "Homeland",
    year: 2011,
    genre: ["Drama", "Thriller"],
    rating: 8.3,
    description:
      "A CIA officer becomes convinced that a war hero who has been turned by Al‑Qaeda is planning to attack the United States.",
    poster: Homeland,
    creator: "Alex Gansa, Howard Gordon",
    cast: ["Claire Danes", "Damian Lewis", "Mandy Patinkin"],
    seasons: 8,
    episodes: 96,
    language: "English",
  },
  {
    id: 43,
    title: "Narcos",
    year: 2015,
    genre: ["Crime", "Drama"],
    rating: 8.8,
    description:
      "A chronicle of the rise and fall of the notorious Colombian drug lord Pablo Escobar and the law enforcement agents who pursued him.",
    poster: Narcos,
    creator: "Carlo Bernard, Chris Brancato, Doug Miro",
    cast: ["Pedro Pascal", "Wagner Moura", "Boyd Holbrook"],
    seasons: 3,
    episodes: 30,
    language: "English, Spanish",
  },
  {
    id: 44,
    title: "The Marvelous Mrs. Maisel",
    year: 2017,
    genre: ["Comedy", "Drama"],
    rating: 8.7,
    description:
      "A 1950s housewife discovers a talent for stand‑up comedy and pursues a career in the male‑dominated world of comedy.",
    poster: TheMarvelousMrsMaisel,
    creator: "Amy Sherman‑Palladino",
    cast: ["Rachel Brosnahan", "Alex Borstein", "Michael Zegen"],
    seasons: 5,
    episodes: 43,
    language: "English",
  },
  {
    id: 45,
    title: "The Good Place",
    year: 2016,
    genre: ["Comedy", "Fantasy"],
    rating: 8.2,
    description:
      "A woman finds herself in the afterlife, but she soon realizes she was sent there by mistake and must try to become a better person.",
    poster: TheGoodPlace,
    creator: "Michael Schur",
    cast: ["Kristen Bell", "William Jackson Harper", "Ted Danson"],
    seasons: 4,
    episodes: 53,
    language: "English",
  },
  {
    id: 46,
    title: "Brooklyn Nine‑Nine",
    year: 2013,
    genre: ["Comedy"],
    rating: 8.4,
    description:
      "A comedy series following the detectives of the 99th Precinct in Brooklyn as they solve crimes and deal with their eccentric colleagues.",
    poster: BrooklynNineNine,
    creator: "Dan Goor, Michael Schur",
    cast: ["Andy Samberg", "Stephanie Beatriz", "Terry Crews"],
    seasons: 8,
    episodes: 153,
    language: "English",
  },
  {
    id: 47,
    title: "The Haunting of Hill House",
    year: 2018,
    genre: ["Horror", "Drama"],
    rating: 8.6,
    description:
      "Flashing between past and present, a fractured family confronts haunting memories of their old home and the terrifying events that drove them from it.",
    poster: TheHauntingOfHillHouse,
    creator: "Mike Flanagan",
    cast: ["Michiel Huisman", "Carla Gugino", "Henry Thomas"],
    seasons: 1,
    episodes: 10,
    language: "English",
  },
  {
    id: 48,
    title: "The Pacific",
    year: 2010,
    genre: ["War", "Drama"],
    rating: 8.3,
    description:
      "The experiences of three U.S. Marines during the Pacific campaign of World War II, from their first battles to the aftermath of the conflict.",
    poster: ThePacific,
    creator: "Bruce C. McKenna, Tom Hanks, Steven Spielberg",
    cast: ["James Badge Dale", "Joseph Mazzello", "Jon Seda"],
    seasons: 1,
    episodes: 10,
    language: "English",
  },
  {
    id: 49,
    title: "Boardwalk Empire",
    year: 2010,
    genre: ["Crime", "Drama"],
    rating: 8.6,
    description:
      "An Atlantic City politician during the Prohibition era builds a criminal empire while balancing his public and private lives.",
    poster: BoardwalkEmpire,
    creator: "Terence Winter",
    cast: ["Steve Busemi", "Michael Pitt", "Kelly Macdonald"],
    seasons: 5,
    episodes: 56,
    language: "English",
  },
  {
    id: 50,
    title: "The Leftovers",
    year: 2014,
    genre: ["Drama", "Mystery"],
    rating: 8.3,
    description:
      "Three years after a global event causes 2% of the world's population to suddenly vanish, the remaining residents of a small town struggle to move on.",
    poster: TheLeftovers,
    creator: "Damon Lindelof, Tom Perrotta",
    cast: ["Justin Theroux", "Carrie Coon", "Amy Brenneman"],
    seasons: 3,
    episodes: 28,
    language: "English",
  },
  {
    id: 51,
    title: "Project Hail Mary",
    year: 2026,
    genre: ["Fiction", "Sci-Fi"],
    rating: 8.3,
    description:
      "Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction… but an unexpected friendship means he may not have to do it alone.",
    poster: hail,
    creator: "Phil Lord",
    cast: ["Ryan Gosling", "James Ortiz", "Amy Brenneman"],
    language: "English",
  },
  {
    id: 52,
    title: "The Sheep Detectives",
    year: 2026,
    genre: ["Fiction", "Family"],
    rating: 7.5,
    description:
      "George Hardy, a shepherd, loves his sheep and raises them only for their wool. Every night he reads aloud a murder mystery, pretending his sheep can understand, never suspecting that not only can they understand but they argue for hours afterwards about whodunnit. When George is found dead under mysterious circumstances, the sheep realise at once that it was a murder and think they know everything about how to go about solving it. The local cop Tim Derry, on the other hand, has never solved a serious crime in his life, so the sheep conclude they will have to solve it themselves, even if it means leaving their meadow for the first time and facing the fact that the human world isn’t as simple as it appears in books.",
    poster: sheep,
    creator: "Kyle Balda",
    cast: ["Hugh Jackman", "Emma Thompson", "Amy Brenneman"],
    language: "English",
  },
  {
    id: 53,
    title: "Nuremberg",
    year: 2026,
    genre: ["history", "Drama"],
    rating: 7.4,
    description:
      "American psychiatrist Douglas Kelley, tasked with determining whether Nazi prisoners are fit to stand trial for their war crimes, finds himself in a complex battle of wits with Hitler’s right-hand man Hermann Göring.",
    poster: nurnberg,
    creator: "James Vanderbilt",
    cast: ["Russell Crowe", "Rami Malek"],
    language: "English",
  },
];
